import { describe, expect, it } from "vitest";
import { MAX_INIT_DATA_AGE_MS, verifyInitData } from "@/lib/telegram/init-data";

/**
 * The vector below is **fixed**, not generated by this file.
 *
 * A test that signs its input with the code under test proves only that the code agrees with
 * itself: flip the key and message in the secret derivation and such a test still passes, while
 * every real Telegram payload is rejected. This hash was produced by an independent
 * implementation (Python's `hmac`) from Telegram's published algorithm, so it fails if the
 * algorithm here drifts in any direction.
 */
const BOT_TOKEN = "123456:TEST-BOT-TOKEN-NOT-REAL";
const USER_JSON = '{"id":42424242,"first_name":"Chris","username":"Chris_Dev","language_code":"en"}';
const AUTH_DATE_SECONDS = 1757289600;
const VALID_HASH = "75d8d2d3db93a979238d51f3188460176c0b66b797192ca329f7e5ca1df2d5ae";

const VALID_INIT_DATA =
  `auth_date=${AUTH_DATE_SECONDS}` +
  `&query_id=AAF_test_query` +
  `&user=${encodeURIComponent(USER_JSON)}` +
  `&hash=${VALID_HASH}`;

/** A moment inside the freshness window, so a passing case is not passing by accident of "now". */
const JUST_AFTER = new Date(AUTH_DATE_SECONDS * 1000 + 30_000);

describe("verifyInitData", () => {
  it("accepts a payload signed with the bot token", () => {
    const result = verifyInitData(VALID_INIT_DATA, BOT_TOKEN, JUST_AFTER);

    expect(result).not.toBeNull();
    expect(result?.telegramUserId).toBe("42424242");
    expect(result?.authDate.getTime()).toBe(AUTH_DATE_SECONDS * 1000);
  });

  it("lower-cases the username, matching how the bot's allowlist holds one", () => {
    // "Chris_Dev" in the payload. The allowlist stores usernames lower-cased, so a caller
    // comparing the two must not have to remember to fold it a second time.
    expect(verifyInitData(VALID_INIT_DATA, BOT_TOKEN, JUST_AFTER)?.username).toBe("chris_dev");
  });

  it("rejects a payload signed with a different bot token", () => {
    // The failure a fork hits, and the one that matters most: another bot's signed payload must
    // not authenticate against this bot's users.
    expect(verifyInitData(VALID_INIT_DATA, "999999:SOME-OTHER-BOT", JUST_AFTER)).toBeNull();
  });

  it("rejects a tampered field", () => {
    // Changing the user id is the whole attack: a valid signature over someone else's account.
    // Every field is covered by the check string, so this must not verify.
    const tampered = VALID_INIT_DATA.replace("42424242", "99999999");

    expect(verifyInitData(tampered, BOT_TOKEN, JUST_AFTER)).toBeNull();
  });

  it("rejects an added field the signature does not cover", () => {
    // Telegram keeps adding fields, so the check string is built from everything present rather
    // than from a known list. An injected one therefore breaks the hash instead of riding along.
    expect(verifyInitData(`${VALID_INIT_DATA}&is_premium=true`, BOT_TOKEN, JUST_AFTER)).toBeNull();
  });

  it("rejects a missing hash", () => {
    const withoutHash = `auth_date=${AUTH_DATE_SECONDS}&user=${encodeURIComponent(USER_JSON)}`;

    expect(verifyInitData(withoutHash, BOT_TOKEN, JUST_AFTER)).toBeNull();
  });

  it("rejects a hash that is not hex", () => {
    // `Buffer.from(s, "hex")` silently truncates at the first invalid pair rather than throwing,
    // and `timingSafeEqual` throws on a length mismatch. Neither may reach the caller.
    const badHash = VALID_INIT_DATA.replace(VALID_HASH, "z".repeat(VALID_HASH.length));

    expect(verifyInitData(badHash, BOT_TOKEN, JUST_AFTER)).toBeNull();
  });

  it("rejects a payload older than the freshness window", () => {
    // Without this bound one captured string is a permanent credential. It travels in a header
    // and nothing in it expires on its own.
    const tooLate = new Date(AUTH_DATE_SECONDS * 1000 + MAX_INIT_DATA_AGE_MS + 1_000);

    expect(verifyInitData(VALID_INIT_DATA, BOT_TOKEN, tooLate)).toBeNull();
  });

  it("still accepts a payload hours into a session", () => {
    // Telegram does not re-sign `initData` while the app is open, so a window shorter than a
    // plausible session locks the page out of its own API with no way back but a relaunch. This
    // is the case an "obviously safer" one-hour window silently breaks.
    const hoursLater = new Date(AUTH_DATE_SECONDS * 1000 + 6 * 60 * 60 * 1000);

    expect(verifyInitData(VALID_INIT_DATA, BOT_TOKEN, hoursLater)).not.toBeNull();
  });

  it("accepts a payload at the edge of the freshness window", () => {
    const atTheEdge = new Date(AUTH_DATE_SECONDS * 1000 + MAX_INIT_DATA_AGE_MS - 1_000);

    expect(verifyInitData(VALID_INIT_DATA, BOT_TOKEN, atTheEdge)).not.toBeNull();
  });

  it("rejects a payload dated in the future", () => {
    // A clock is wrong somewhere, so the age check cannot be trusted to expire it either. One
    // minute of slack absorbs ordinary drift; ten does not.
    const wellBefore = new Date(AUTH_DATE_SECONDS * 1000 - 10 * 60_000);

    expect(verifyInitData(VALID_INIT_DATA, BOT_TOKEN, wellBefore)).toBeNull();
  });

  it("tolerates a minute of clock drift", () => {
    const slightlyBefore = new Date(AUTH_DATE_SECONDS * 1000 - 30_000);

    expect(verifyInitData(VALID_INIT_DATA, BOT_TOKEN, slightlyBefore)).not.toBeNull();
  });

  it("rejects an empty payload or an empty token", () => {
    // An unset TELEGRAM_BOT_TOKEN must fail closed. `createHmac` accepts an empty key perfectly
    // happily and would produce a stable digest anyone could reproduce.
    expect(verifyInitData("", BOT_TOKEN, JUST_AFTER)).toBeNull();
    expect(verifyInitData(VALID_INIT_DATA, "", JUST_AFTER)).toBeNull();
  });
});

describe("verifyInitData: the user field", () => {
  /** Re-sign a set of fields so the shape of `user` can be varied without breaking the hash.
   *  Only used for cases where the *signature* is not what is under test. */
  const sign = async (fields: Record<string, string>): Promise<string> => {
    const { createHmac } = await import("node:crypto");
    const dcs = Object.entries(fields)
      .map(([k, v]) => `${k}=${v}`)
      .sort()
      .join("\n");
    const secret = createHmac("sha256", "WebAppData").update(BOT_TOKEN).digest();
    const hash = createHmac("sha256", secret).update(dcs).digest("hex");
    return `${new URLSearchParams({ ...fields, hash }).toString()}`;
  };

  it("rejects a correctly signed payload carrying no user", () => {
    // A keyboard-button Mini App gets a signed payload with no user in it at all. It must not
    // authenticate as anybody, which is why the launch surfaces are menu and inline buttons.
    return sign({ auth_date: String(AUTH_DATE_SECONDS), query_id: "AAF_test" }).then((raw) => {
      expect(verifyInitData(raw, BOT_TOKEN, JUST_AFTER)).toBeNull();
    });
  });

  it("rejects a user that is not JSON", () => {
    return sign({ auth_date: String(AUTH_DATE_SECONDS), user: "not json" }).then((raw) => {
      expect(verifyInitData(raw, BOT_TOKEN, JUST_AFTER)).toBeNull();
    });
  });

  it("rejects a user whose id is a string", () => {
    // `String(id)` would happily turn "42424242" into the right-looking value, so the type is
    // checked before the conversion rather than after it.
    return sign({
      auth_date: String(AUTH_DATE_SECONDS),
      user: '{"id":"42424242"}',
    }).then((raw) => {
      expect(verifyInitData(raw, BOT_TOKEN, JUST_AFTER)).toBeNull();
    });
  });

  it("rejects a non-positive id", () => {
    // Private chat ids are the user's own id and are always positive. Zero is what a coerced
    // empty value looks like, and it is a perfectly safe integer.
    return sign({ auth_date: String(AUTH_DATE_SECONDS), user: '{"id":0}' }).then((raw) => {
      expect(verifyInitData(raw, BOT_TOKEN, JUST_AFTER)).toBeNull();
    });
  });

  it("rejects a blank auth_date rather than dating the payload to 1970", () => {
    // `Number("")` is 0, which is finite and would read as merely very stale. Matched as text
    // first for exactly this reason -- the same trap `menuRegistrations` documents.
    return sign({ auth_date: "", user: USER_JSON }).then((raw) => {
      expect(verifyInitData(raw, BOT_TOKEN, JUST_AFTER)).toBeNull();
    });
  });

  it("carries start_param through when the app was opened from a direct link", () => {
    return sign({
      auth_date: String(AUTH_DATE_SECONDS),
      user: USER_JSON,
      start_param: "fare",
    }).then((raw) => {
      expect(verifyInitData(raw, BOT_TOKEN, JUST_AFTER)?.startParam).toBe("fare");
    });
  });
});
