import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import type { Prisma } from "@prisma/client";
import { getAuthUserId } from "@/lib/session";
import { billActionSchema } from "@/lib/validations";
import { advanceToNextUnpaidOccurrence } from "@/lib/bill-utils";
import { getScheduleContext, matchScheduledLabel } from "@/lib/schedule-server";

export async function POST(
  request: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  const userId = await getAuthUserId();
  if (userId instanceof NextResponse) return userId;

  const { id } = await params;

  try {
    const bill = await prisma.scheduledTransaction.findUnique({
      where: { id },
      include: { category: true, labels: { include: { label: true } } },
    });

    if (!bill || bill.userId !== userId) {
      return NextResponse.json({ error: "Bill not found" }, { status: 404 });
    }

    const body = await request.json();
    const { action, dueDate: dueDateStr, transactionId: existingTransactionId, snoozeDays } = billActionSchema.parse(body);
    const dueDate = new Date(dueDateStr);

    const originalStartDay = bill.startDate.getDate();

    /**
     * Resolve the bill's next due date after a terminal log has been written.
     *
     * Advancing from the *acted-on* occurrence loses data: occurrences earlier
     * than the result are never regenerated by getPendingRemindersForUser (it
     * only walks forward from nextDueDate), so paying or skipping an occurrence
     * out of order silently discarded every unpaid one before it. Walk from the
     * current nextDueDate to the earliest occurrence with no terminal log
     * instead.
     *
     * Takes a row lock on the bill first. Postgres defaults to READ COMMITTED,
     * so without it two concurrent actions on the same bill would both start
     * from the nextDueDate read before either transaction began, each miss the
     * other's uncommitted log, and the later commit would clobber the earlier
     * one with a stale date. The lock serialises them, and re-reading inside
     * the lock means the second sees the first's committed result.
     *
     * Call after inserting this action's log so the walk counts it too.
     */
    const resolveNextDueDate = async (tx: Prisma.TransactionClient) => {
      const [locked] = await tx.$queryRaw<{ next_due_date: Date }[]>`
        SELECT next_due_date FROM scheduled_transactions WHERE id = ${id} FOR UPDATE
      `;

      const logs = await tx.scheduledTransactionLog.findMany({
        where: { scheduledTransactionId: bill.id },
        select: { dueDate: true, status: true },
      });

      return advanceToNextUnpaidOccurrence(
        locked?.next_due_date ?? bill.nextDueDate,
        bill.frequency,
        originalStartDay,
        bill.customIntervalDays,
        logs,
        { endDate: bill.endDate },
      );
    };

    if (action === "pay") {
      // Resolve labels: bill labels take priority over scheduled auto-labels
      const billLabelIds = (bill.labels ?? [])
        .filter((bl) => bl.label.applicableTo === "BOTH" || bl.label.applicableTo === bill.type)
        .map((bl) => bl.labelId);
      let transactionLabelIds: string[] = [];

      if (billLabelIds.length > 0) {
        transactionLabelIds = billLabelIds;
      } else {
        const paymentDate = new Date();
        const ctx = await getScheduleContext(userId);
        const scheduledLabelId = ctx ? matchScheduledLabel(paymentDate, ctx, bill.type) : null;
        if (scheduledLabelId) transactionLabelIds = [scheduledLabelId];
      }

      // Atomic: create transaction, log payment, advance bill. Prevents
      // partial writes that leave nextDueDate stale or logs orphaned.
      const transactionId = await prisma.$transaction(async (tx) => {
        const transaction = await tx.transaction.create({
          data: {
            amount: bill.amount,
            description: bill.description,
            type: bill.type,
            date: new Date(),
            categoryId: bill.categoryId,
            userId,
            billId: bill.id,
            ...(transactionLabelIds.length > 0 && {
              labels: {
                create: transactionLabelIds.map((labelId) => ({ labelId })),
              },
            }),
          },
        });

        await tx.scheduledTransactionLog.create({
          data: {
            scheduledTransactionId: bill.id,
            dueDate,
            status: "PAID",
            actionDate: new Date(),
            transactionId: transaction.id,
          },
        });

        // Earliest still-unpaid occurrence, not simply the one just paid
        const nextDue = await resolveNextDueDate(tx);

        await tx.scheduledTransaction.update({
          where: { id },
          data: {
            ...(nextDue && { nextDueDate: nextDue }),
            // null means no valid occurrence left (past endDate or none found)
            ...(nextDue === null && { isActive: false }),
          },
        });

        return transaction.id;
      });

      return NextResponse.json({ message: "Bill paid", transactionId });
    }

    if (action === "pay_existing") {
      // Verify the target transaction belongs to the authenticated user
      const existingTx = await prisma.transaction.findFirst({
        where: { id: existingTransactionId!, userId },
        select: { id: true },
      });
      if (!existingTx) {
        return NextResponse.json({ error: "Transaction not found" }, { status: 404 });
      }

      // Atomic: log payment, link txn to bill, advance bill — one commit.
      await prisma.$transaction(async (tx) => {
        await tx.scheduledTransactionLog.create({
          data: {
            scheduledTransactionId: bill.id,
            dueDate,
            status: "PAID",
            actionDate: new Date(),
            transactionId: existingTx.id,
          },
        });
        await tx.transaction.update({
          where: { id: existingTx.id },
          data: { billId: bill.id },
        });

        const nextDue = await resolveNextDueDate(tx);

        await tx.scheduledTransaction.update({
          where: { id },
          data: {
            ...(nextDue && { nextDueDate: nextDue }),
            ...(nextDue === null && { isActive: false }),
          },
        });
      });

      return NextResponse.json({ message: "Bill marked as paid" });
    }

    if (action === "snooze") {
      // Snooze for N days (default 1) — do NOT advance nextDueDate
      const days = snoozeDays ?? 1;
      const snoozeUntil = new Date();
      snoozeUntil.setDate(snoozeUntil.getDate() + days);
      snoozeUntil.setHours(0, 0, 0, 0);

      await prisma.scheduledTransactionLog.create({
        data: {
          scheduledTransactionId: bill.id,
          dueDate,
          status: "SNOOZED",
          actionDate: new Date(),
          snoozeUntil,
        },
      });

      return NextResponse.json({ message: `Bill snoozed for ${days} day${days > 1 ? "s" : ""}` });
    }

    if (action === "skip") {
      // Atomic: log skip + advance bill together.
      await prisma.$transaction(async (tx) => {
        await tx.scheduledTransactionLog.create({
          data: {
            scheduledTransactionId: bill.id,
            dueDate,
            status: "SKIPPED",
            actionDate: new Date(),
          },
        });

        const nextDue = await resolveNextDueDate(tx);

        await tx.scheduledTransaction.update({
          where: { id },
          data: {
            ...(nextDue && { nextDueDate: nextDue }),
            ...(nextDue === null && { isActive: false }),
          },
        });
      });

      return NextResponse.json({ message: "Bill skipped" });
    }

    return NextResponse.json({ error: "Invalid action" }, { status: 400 });
  } catch (error) {
    if (error instanceof Error && error.name === "ZodError") {
      return NextResponse.json({ error: "Invalid input" }, { status: 400 });
    }
    return NextResponse.json({ error: "Failed to process action" }, { status: 500 });
  }
}
