-- Drops the label -> category restriction introduced by 20260912120000_add_label_categories.
--
-- A FORWARD migration, not an edit to the one that created the table. That migration is applied to
-- production, and `scripts/check-migration-drift.ts` fails a deploy naming any migration applied to
-- the database that the checkout does not contain. Deleting the directory would therefore break
-- every deploy rather than undo anything -- see issue #192.
--
-- WHY THIS IS BEING REMOVED, so nobody reintroduces it unchanged (issue #303):
--
-- The restriction was opt-in: a label could narrow itself, but a category had no way to exclude
-- labels that never opted in. With six of eight labels unrestricted, the picker still offered seven
-- of eight labels on Transportation, including the Shopee label the feature was opened to exclude.
-- It shipped without fixing its own motivating example.
--
-- The direction of the join table was NOT the problem and is not what changes by dropping it:
-- label_categories carried both label_id and category_id, so "which labels may this category use"
-- was always answerable from it. What was missing was a screen and an opt-OUT default, and a future
-- attempt should decide the DEFAULT (empty means every category, versus a category owning its list
-- and needing a backfill) before recreating anything.
--
-- Dropping the table loses three rows of real configuration, recorded here because a dropped table
-- takes its data with it:
--
--   Pickleball Budget -> Fun, Shopping
--   TNVC              -> Transportation
--
-- The foreign keys are ON DELETE CASCADE from both labels and categories, so no other table
-- references this one and nothing else needs unwinding. Transactions, bills and quick tiles keep
-- every label they carry: this table only ever gated which labels were OFFERED, never which were
-- attached.
DROP TABLE IF EXISTS "label_categories";
